import { TastingNoteEntryInterface, LoungeNoteInterface } from "@/type/TastingNoteInterface";

/**
 * 테이스팅 노트의 개별 항목 (내 기록용)
 * 기존 WhiskyEntry를 TastingNoteEntryInterface로 평준화하여 대체합니다.
 */
export type WhiskyEntry = TastingNoteEntryInterface;

export const initialWhiskies: WhiskyEntry[] = [
  {
    id: "w1",
    category: "whisky",
    formType: "basic",
    whiskyName: "라가불린 16년",
    whiskyNameEn: "Lagavulin 16",
    date: "2026.04.12",
    weatherValue: "비 내리는 저녁",
    moodValue: "차분하고 사색적",
    abvValue: "43% ABV",
    additionalValue: "피트향이 강한 것을 선호합니다.",
    foodName: "다크 초콜릿",
    bartenderWord: "깊은 바다의 안개처럼 묵직한 스모키함이 일품인 위스키입니다.",
    shared: true,
    status: "평가완료",
    ratedAt: "2026.04.13",
    nose: "강렬한 피트 스모크, 요오드, 해초의 향이 코를 찌릅니다.",
    palate: "풍부한 과일의 달콤함 뒤에 밀려오는 묵직한 탄탄함.",
    finish: "매우 길고 우아한 무화과와 스모키한 여운.",
    rating: 4.5,
  },
  {
    id: "w2",
    category: "whisky",
    formType: "basic",
    whiskyName: "글렌피딕 18년",
    whiskyNameEn: "Glenfiddich 18",
    date: "2026.04.20",
    weatherValue: "맑은 봄밤",
    moodValue: "설레는 기대감",
    abvValue: "40% ABV",
    additionalValue: "달콤한 과일 향이 났으면 좋겠어요.",
    foodName: "사과 파이",
    bartenderWord: "셰리 캐스크의 달콤함과 잘 익은 사과의 풍미가 조화롭습니다.",
    shared: false,
    status: "미평가",
    rating: 0,
  },
  {
    id: "w3",
    category: "whisky",
    formType: "free",
    whiskyName: "히비키 하모니",
    whiskyNameEn: "Hibiki Harmony",
    date: "2026.04.25",
    weatherValue: "안개 낀 새벽",
    moodValue: "고요한 명상",
    abvValue: "43% ABV",
    additionalValue: "부드러운 블렌디드를 원합니다.",
    foodName: "화이트 초콜릿",
    bartenderWord: "일본 위스키의 섬세함과 오케스트라 같은 조화를 느껴보세요.",
    shared: true,
    status: "미평가",
    rating: 0,
  },
  {
    id: "w5",
    category: "whisky",
    formType: "free",
    whiskyName: "발베니 12년 더블우드",
    whiskyNameEn: "Balvenie 12 DoubleWood",
    date: "2026.04.28",
    weatherValue: "화창한 오후",
    moodValue: "기분 좋은 휴식",
    abvValue: "40% ABV",
    additionalValue: "부담 없이 마실 수 있는 달콤한 위스키.",
    foodName: "바닐라 아이스크림",
    bartenderWord: "꿀의 달콤함과 부드러운 목넘김이 매력적인 베스트셀러입니다.",
    shared: true,
    status: "평가완료",
    ratedAt: "2026.04.29",
    memo: "정말 부드럽고 달콤합니다. 입문자에게 최고인 것 같아요. 바닐라 아이스크림과도 찰떡궁합이네요.",
    rating: 4.0,
  },
  {
    id: "c1",
    category: "cocktail",
    formType: "basic",
    cocktailName: "올드 패션드",
    date: "2026.05.02",
    weatherValue: "선선한 가을 밤",
    moodValue: "클래식한 분위기",
    additionalValue: "설탕을 조금만 넣어주세요.",
    foodName: "오렌지 필",
    bartenderWord: "위스키의 풍미를 가장 정석으로 즐길 수 있는 칵테일입니다.",
    shared: false,
    status: "미평가",
    rating: 0,
  }
];

/**
 * 라운지 게시판 데이터 인터페이스
 */
export type LoungeNote = LoungeNoteInterface;

export const loungeNotes: LoungeNote[] = [
  {
    id: "n1",
    author: "달콤한밤",
    category: "whisky",
    formType: "basic",
    whiskyName: "발베니 12년 더블우드",
    whiskyNameEn: "Balvenie 12 DoubleWood",
    likes: 12,
    rotate: 0,
    pinColor: "#c0392b",
    nose: "달콤한 꿀, 부드러운 바닐라와 은은한 오크.",
    palate: "넛맥과 시나몬의 스파이스, 셰리의 달콤함.",
    finish: "따뜻하고 부드럽게 감도는 잔향.",
    createdAt: "2026.04.10",
    rating: 4,
  },
  {
    id: "n2",
    author: "피트러버",
    category: "whisky",
    formType: "free",
    whiskyName: "라프로익 10년",
    whiskyNameEn: "Laphroaig 10",
    memo: "강렬한 병원 소독약 냄새 뒤에 숨겨진 해초와 짭짤한 바다의 맛. 피트의 정수가 무엇인지 보여주는 완벽한 한 잔.",
    likes: 34,
    rotate: 0,
    pinColor: "#27496d",
    createdAt: "2026.04.12",
    rating: 4.5,
  },
  {
    id: "n5",
    author: "셰리캐스크",
    category: "whisky",
    formType: "basic",
    whiskyName: "아벨라워 아부나흐",
    whiskyNameEn: "Aberlour A'bunadh",
    likes: 42,
    rotate: 0,
    pinColor: "#7d3c98",
    nose: "오렌지 껍질, 블랙 체리, 말린 과일.",
    palate: "묵직한 올로로소 셰리, 다크 초콜릿, 스파이스.",
    finish: "강렬하고 긴 스파이시 셰리 피니시.",
    createdAt: "2026.04.18",
    rating: 5,
  },
  {
    id: "n11",
    author: "칵테일매니아",
    category: "cocktail",
    formType: "basic",
    cocktailName: "마티니",
    likes: 15,
    rotate: 0,
    pinColor: "#1f618d",
    nose: "진의 날카로운 향과 베르무트의 허브향.",
    palate: "깔끔하고 드라이한 맛이 일품.",
    finish: "올리브의 짭짤함이 남는 깔끔한 피니시.",
    createdAt: "2026.05.01",
    rating: 4.5,
  }
];
